### ISSUE TITLE
cron job and RRD problem

### ISSUE THREAD

**Issue by i0dev** [benjamin-robertson/observium#11]
Thank you so much for reviewing and merging my PR. I just have one more thing I was having some issues with, it has to do with the cron jobs.

For Observium, the poller-wrapper discovers new devices and adds them to `/opt/observium/rrd/`, but in order for the graphs and metrics for these devices to be displayed on the web panel, the owner needs to be `www-data`

that's why I had re-written the cron jobs to be done with corn::job::multiple so I could specifically set the user for the poller-wrapper.py job to be `www-data`, I don't know if your way can specify a user to run the job instead of root.

That worked for me, but there might be a better way of doing this too that I am unaware of.

**Comment by benjamin-robertson** [comment]
Hi Andrew;

I've run up a new install of Obversium using the module on Ubuntu 22.04. I don't seem to have those issues.

Under https://docs.observium.org/install_debian/ they have the poller-wrapper script running as root.
```
# Run multithreaded poller wrapper every 5 minutes
*/5 *     * * *   root    /opt/observium/poller-wrapper.py >> /dev/null 2>&1
```

What you should check locally is the file permissions on /opt/observium/rrd/ mine are as follows.
`drwxrwxr-x 12 ubuntu ubuntu 4.0K Jun 14 05:48 observium`
`drwxr-xr-x   3 www-data www-data 4.0K Jun 14 05:50 rrd`
```
root@ip-172-31-8-189:/opt/observium/rrd# ls -lh
total 464K
drwxr-xr-x 2 root root 4.0K Jun 14 05:50 127.0.0.1
-rw-r--r-- 1 root root 341K Jun 14 06:20 poller-wrapper.rrd
-rw-r--r-- 1 root root 115K Jun 14 06:20 poller-wrapper_count.rrd
```

All the files under /opt/observium/rrd/ are readable by everyone. But only writable by root. Which is probably best as the web server shouldn't need to update these files.

If that's all okay, it could be apparmor or selinux (RHEL) blocking webserver access to this directory.

**Comment by i0dev** [comment]
Okay, I think this is only an issue for me because of our strict blocking of access to directories from the public.

You can close this issue, thank you for the detailed reply
